"""Make department_id nullable

Revision ID: 2df0eeb30cc0
Revises: 5616e9d1660e
Create Date: 2025-11-04 11:39:15.819314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df0eeb30cc0'
down_revision = '5616e9d1660e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    with op.batch_alter_table('about_us_images', schema=None) as batch_op:
        batch_op.alter_column('filepath',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('alumnis', schema=None) as batch_op:
        batch_op.alter_column('current_title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=600),
               existing_nullable=True)
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('clubs_and_societies', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('subject_selections', schema=None) as batch_op:
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject_selections', schema=None) as batch_op:
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=600),
               existing_nullable=False)

    with op.batch_alter_table('clubs_and_societies', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=600),
               existing_nullable=True)

    with op.batch_alter_table('alumnis', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=600),
               existing_nullable=True)
        batch_op.alter_column('current_title',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('about_us_images', schema=None) as batch_op:
        batch_op.alter_column('filepath',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=600),
               existing_nullable=False)

    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    # ### end Alembic commands ###
