"""link subject selections with system, department, and optional track

Revision ID: 5616e9d1660e
Revises: 8ba4c6a6bb60
Create Date: 2025-10-18 15:19:50.996163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5616e9d1660e'
down_revision = '8ba4c6a6bb60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subjects', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_subject_selections_department_id_departments')),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], name=op.f('fk_subject_selections_system_id_systems')),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_subject_selections_track_id_tracks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject_selections'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject_selections')
    # ### end Alembic commands ###
