"""removed title from users model

Revision ID: 8975bf7766ef
Revises: fb3cc5c5446e
Create Date: 2025-10-12 10:03:59.945656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8975bf7766ef'
down_revision = 'fb3cc5c5446e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
