"""added alumni table

Revision ID: 8ba4c6a6bb60
Revises: c87b130cbed4
Create Date: 2025-10-18 11:33:22.662629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba4c6a6bb60'
down_revision = 'c87b130cbed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumnis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('current_title', sa.String(length=200), nullable=True),
    sa.Column('year_of_completion', sa.String(length=10), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=False),
    sa.Column('image_path', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alumnis'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alumnis')
    # ### end Alembic commands ###
