"""removed unique constraint from username

Revision ID: c85cde33fc1b
Revises: 8975bf7766ef
Create Date: 2025-10-12 14:57:23.604599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c85cde33fc1b'
down_revision = '8975bf7766ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs_and_societies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    with op.batch_alter_table('clubs_and_societies', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
