"""Initial tables

Revision ID: fb3cc5c5446e
Revises: b160f3a25f58
Create Date: 2025-10-11 17:11:25.505941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3cc5c5446e'
down_revision = 'b160f3a25f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_subjects_system_id_systems'), 'systems', ['system_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_subjects_system_id_systems'), type_='foreignkey')
        batch_op.drop_column('system_id')

    # ### end Alembic commands ###
